version: '3.7'
services:
  # Todo: Service Pink App
  service:
    container_name: service_pink_app
    restart: always
    build:
      dockerfile: ./docker/pink_app/Dockerfile
      context: .
    environment:
      - NODE_ENV=DEV
    ports:
      - ${PORT}:${PORT}
    volumes:
      - './src:/usr/src/app/src'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://${HOST_APP}:${PORT}/api/v1']
      interval: 60s
      timeout: 2s
      retries: 3
    networks:
      - service_pink_app-network

networks:
  service_pink_app-network:
    driver: bridge
volumes:
  db_data:
    driver: local
